### ISSUE TITLE
Missing html/text field on messages

### ISSUE THREAD

**Issue by steelbrain** [AtomLinter/linter-php#57]
Continuing from https://github.com/atom-community/linter/issues/799

**Comment by steelbrain** [comment]
Here's a screenshot
![clipjwhueaeh6ay](https://cloud.githubusercontent.com/assets/4278113/9054123/f5367972-3a3a-11e5-9bce-301adf25547c.png)

**Comment by NodexTech** [comment]
I also have this bug but reported it to the wrong repo!

**Comment by jpxd** [comment]
Me too!
I hope this will get fixed fast. I need my linter back...

**Comment by gianlucacuomo** [comment]
I confirm the bug on OS X Yosemite

**Comment by robneu** [comment]
+1 seeing the same thing here. Only seems to happen on certain syntax errors.

**Comment by steelbrain** [comment]
I tried and failed to repro this on my machine, what I get is a valid syntax error in my panel near that return. Maybe it's a php version difference?

**Comment by robneu** [comment]
Could be. I'm currently using PHP `5.4.37`. I can flip over to a newer version and see if it makes a difference if that's helpful.

**Comment by steelbrain** [comment]
I've tested this on `PHP 5.6.4-4ubuntu6.2` and `HipHop VM 3.9.0-dev`.

**Comment by steelbrain** [comment]
Anyways, can you provide a raw output of `php -l` of your php version?

**Comment by robneu** [comment]
Here's a raw output of `php -l` on a file with a deliberate syntax error:

```php
PHP Parse error:  syntax error, unexpected 'public' (T_PUBLIC), expecting '{' in /Users/robertneu/GitHub/langile/genlib/inc/class-style-builder.php on line 35

Parse error: syntax error, unexpected 'public' (T_PUBLIC), expecting '{' in /Users/robertneu/GitHub/langile/genlib/inc/class-style-builder.php on line 35
Errors parsing /Users/robertneu/GitHub/langile/genlib/inc/class-style-builder.php
```

**Comment by steelbrain** [comment]
Can someone try this and see if it fixes the problem? https://github.com/AtomLinter/linter-php/pull/58.patch

**Comment by robneu** [comment]
Yup. Working fine for me with that patch applied.

**Comment by steelbrain** [comment]
Waiting on https://github.com/AtomLinter/atom-linter/pull/31 
will use it in that branch and push a release

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-php/pull/58

**Comment by robneu** [comment]
:+1: :100:

**Comment by jeffaustin81** [comment]
Awesome!!!

**Comment by apemsel** [comment]
I have linter 1.3.1 and linter-php 1.0.3 and still see this error. Tried to apply the patch manually but it seams to already be included in this version. Should it work?
PHP 5.5.27 (cli) (built: Jul 29 2015 08:48:15) (OSX 10.11 Build 15A243d)

**Comment by steelbrain** [comment]
@apemsel That is super weird, can you provide the output `php -l` of when you get this error?

**Comment by apemsel** [comment]
php -l controller/iframe_search.php 
    Parse error: parse error in controller/iframe_search.php on line 37

**Comment by steelbrain** [comment]
@apemsel You shouldn't be getting that error :( https://regex101.com/r/kD2nU6/1

**Comment by apemsel** [comment]
This is the exact error I get:
```
Error: Missing html/text field on Linter Response
  at /Users/apemsel/.atom/packages/linter/lib/validate.coffee:24:19
  at Array.forEach (native)
  at Object.module.exports.Validate.messages (/Users/apemsel/.atom/packages/linter/lib/validate.coffee:20:14)
  at MessageRegistry.set (/Users/apemsel/.atom/packages/linter/lib/message-registry.coffee:22:18)
  at /Users/apemsel/.atom/packages/linter/lib/linter-plus.coffee:27:17
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Users/apemsel/.atom/packages/linter/lib/linter-registry.coffee:57:32
```

**Comment by steelbrain** [comment]
@apemsel Can you add a `console.log(messages)` before this line and show us the output? https://github.com/AtomLinter/linter-php/blob/master/lib/main.coffee#L43

**Comment by apemsel** [comment]
Oh my... I restarted Atom after editing main.coffee and sure enough it works now. Sorry to have wasted your time. I was under the impression that updating the packages in atom should also reload them... but maybe not completely
